name: snapshot

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
      - ".github/workflows/**"

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download Slang binaries
        run: |
          curl -L -o slang.zip https://github.com/shader-slang/slang/releases/download/v2025.10.3/slang-2025.10.3-windows-x86_64.zip
          powershell -Command "Expand-Archive -Path slang.zip -DestinationPath slang_temp -Force; if (!(Test-Path -Path .\bin)) { New-Item -ItemType Directory -Path .\bin }; Copy-Item slang_temp\bin\* .\bin -Force; Remove-Item slang_temp -Recurse -Force"

      - name: Set up Clang (x64)
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Configure MSVC (amd64)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Configure CMake (x64)
        run: cmake --preset clang-x64

      
      - name: Build Trails Beyond Horizon Vanilla Plus
        run: cmake --build --preset clang-x64-release --target kai-vanillaplus --verbose
      
      - name: Build YS X Proud Nordics
        run: cmake --build --preset clang-x64-release --target ys10pn --verbose
-
      
      - name: Set up Clang (x86)
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x86

      - name: Configure MSVC (x86)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: Configure CMake (x86)
        run: cmake --preset clang-x86

      - name: Build Trails of Cold Steel II
        run: cmake --build --preset clang-x86-release --target senkiseki32 --verbose


      - name: Prepare Release folder
        run: |
          md githubrelease
          copy build\release\*.addon64 githubrelease\
          copy build32\release\*.addon32 githubrelease\
          copy build\release\*.pdb githubrelease\

      - name: Create a Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: snapshot
          title: RenoDX Snapshot Build (Toru77)
          files: githubrelease/*
